worker_processes auto;

events {
     worker_connections 512;
}

http {
    access_log off;
#     sendfile   on;

    tcp_nopush on;

    tcp_nodelay on;

    upstream api {
        server backend1:9090;
        server backend2:9091;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://api;
        }
    }
}