server:
  port: 9999
spring:
  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO
#    org.postgresql: TRACE
#    com.zaxxer.hikari: TRACE