spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO