server:
  port: ${SERVER_PORT}
spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO
#    org.postgresql: TRACE
#    com.zaxxer.hikari: TRACE